### ISSUE TITLE
Overload style for Base methods

### ISSUE THREAD

**Issue by jagot** [JuliaApproximation/ContinuumArrays.jl#11]
I needed to add `copy` and `copyto!` methods for `MulQuasiArrays`, and nothing worked until I realized that they were not imported from `Base` in `QuasiArrays.jl`, effectively making the copy methods in [`abstractquasiarray.jl`](https://github.com/JuliaApproximation/ContinuumArrays.jl/blob/master/src/QuasiArrays/abstractquasiarray.jl#L421) hidden. It's easy enough to add more imports to `QuasiArrays.jl`, but recently I've started explicitly prepending the name of the module to the method I'm overloading, to decrease confusion, e.g. `Base.copyto!(...) =`. What do you think about this?

**Comment by dlfivefifty** [comment]
No, I use to do this and it adds to code clutter and makes it harder to cope with functions moving to different packages. Also, the current style is consistent with StdLib, and consistency is important for updating quasi arrays with new versions of Julia via diffs.

**Comment by jagot** [comment]
Fair enough.
