### ISSUE TITLE
Derivative -> Diff?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ContinuumArrays.jl#135]
@jagot any opinions on renaming `Derivative` as `Diff`? This would be to be consistent with the use of `diff` for differentiating a quasi-vector.

**Comment by dlfivefifty** [comment]
The other reason is then ApproxFun can use `Derivative` to mean the derivative operator (that is a function of functions)

**Comment by jagot** [comment]
Fine by me, as long as you put a deprecation warning in so I have a chance of catching the change in all places.
