### ISSUE TITLE
Move out Splines?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ContinuumArrays.jl#16]
@jagot do you use the splines here, or should they be moved out and this made a "minimal" package?

**Comment by jagot** [comment]
No, I'm fine with moving out all specific implementations!

**Comment by dlfivefifty** [comment]
Maybe I'll just leave it for now as `BSpline` in BSplinesQuasi.jl looks a bit "heavy", so there may still be a role for lightweight splines....

**Comment by jagot** [comment]
Also fine; BSplinesQuasi.jl is not mathematically pure either, although I hope you'll be able to help me improve that point :)

**Comment by dlfivefifty** [comment]
To be honest I've never really been into splines... I can never remember what the difference between B-Spline, Bezier splines, and just "splines" is 🤣

I think I'm really interested in just affine FEM at the moment with `LinearSpline` being the linear case. Where would you see this living? Perhaps the 1D case can continue to live here (and therefore the tests are meaningful), removing the more general `Spline` term, with tetrahedra in a separate case.

**Comment by jagot** [comment]
I think the changes you mention are good.

The good thing about splines is that they are very "malleable", you can very easily adapt your basis to the problem at hand (much more so than finite-elements, at least what I have seen so far). The bad thing of course is that the overlap matrix is no longer diagonal, so everything becomes generalized.

I think B-spline: local, Beziér: global, spline: [draftsman's tool](https://en.wikipedia.org/wiki/Flat_spline) :)

![spline](https://upload.wikimedia.org/wikipedia/commons/f/fd/Spline_%28PSF%29.png)
