### ISSUE TITLE
Change of variables

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ContinuumArrays.jl#17]
How do we represent change of variables? E.g., P_n(2x-1) for Legendre on 0..1. 

I think the "right" way to do this is to treat change of variables also as quasi-matrices. That is the map `u ->  (x -> u(2x-1))` is a linear operator from functions on `-1..1` to functions on `0..1`. Formally this can be thought of as convolution with a delta function:
$$
\int_{-1}^1 \delta(y - (2x-1)) u(y) dy 
$$
This hints that we can represent such an operator as:
```julia
x, y = Inclusion(0..1), Inclusion(-1..1)
R = δ.(y' .- (2.*x .- 1))
R * Legendre() 
```

How does this interact with other operators like derivative? I think quite nicely: we would just need a simplifying relationship so that:
```julia
D = Derivative(x)
D*R == 2R*D
```
Then full materialize would automatically reduce:
```julia
D*R*Legendre() == 2R*D*Legendre() == 2R*Jacobi(1,1)*B
```
where B is some banded matrix. 

PS: this assumes the current `DiracDelta <: AbstractQuasiVector` being replaced with a `δ` that behaves like a function, and then `δ.(Inclusion(d) .- x)` replacing `DiracDelta(d,x)`.

PPS: We would need to make sure constant multiplication is "passed through" to the matrix.

PPPS: The simpler approach is to do what ApproxFun did and encode the domain inside `Legendre`. This has the effect that every space needs to know about coordinate transformations. This worked but I believe the `R` approach above to be more versatile (it completely decouples coordinate transformations from bases), and so crazy that I really want to to do it 🤣

**Comment by dlfivefifty** [comment]
@jagot Any thoughts? Have you dealt with thisin FEDVRQuasi.jl?

**Comment by jagot** [comment]
No, I have not implemented anything like that yet, but I will need it soonish. The variable transformation I need (log r for small r, and simply r for large r) probably needs a numeric Jacobian (I guess).

The reason for this weird grid us that the eigenfunctions of the discrete spectrum are polynomials*exp(-r) whereas those of the continuous spectrum are ~exp(im*k.r).

**Comment by dlfivefifty** [comment]
I think we should leverage automatic differentiation for  computation of Jacobians. I’m not sure whether reverse (Zygote.jl) or forward mode (ForwardDiff.jl) is more appropriate though.

What’s more involved is inverting the map. I think this could be done on a case-by-case basis. The nice thing about the linear operator approach is we should get conposability for free: for example, the affine transformation may be better written as
```Julia
z = Inclusion(-0.5..0.5)
δ.(z’ .- (x .- 1)) * δ.(y’ .- (2z))
```

What I’m not sure about is whether representing these as a ` BroadcastQuasiArray ` is that good idea, with the alternative being a special type ` Map <: QuasiMatrix ` .

**Comment by jagot** [comment]
Without understanding the finer details, I'd say that the transformation deserves its own type. I don't think of variable transformations as operators/functionals; I'm still looking for the same function/vector, just with a reparameterization of the Hilbert space. Does that make sense?

**Comment by dlfivefifty** [comment]
They will definitely still be operators (quasi matrices) as there is no benefit to treating them separately, where treating them like operators allows so to leverage the existing code.

**Comment by dlfivefifty** [comment]
Actually, maybe it's better as a `view`. That is, we can have:
```julia
x, y = Inclusion(0..1), Inclusion(-1..1)
view(Legendre(),2x.-1,:)
```

**Comment by dlfivefifty** [comment]
Yes! Definitely use views, as its consistent with arrays:
```julia
julia> x = OffsetArray([1,2,3],-1:1) # map from -1:1 to 1:3
3-element OffsetArray(::Array{Int64,1}, -1:1) with eltype Int64 with indices -1:1:
 1
 2
 3

julia> y = randn(3)
3-element Array{Float64,1}:
  1.2384744398934817
 -1.1257377687037258
 -0.4709990597919834

julia> y[x][0] # y[x] is the mapped y
-1.1257377687037258
```

**Comment by dlfivefifty** [comment]
Even better, this interpretation is consistent with Chain rule:
```julia
julia> x = range(0,1; length=1000);

julia> f = exp.(x);

julia> y = Base.IdentityUnitRange(0:499); 

julia> norm(diff(f[2y .+ 1]) - 2diff(f)[2y .+ 1][1:end-1]) # 2y .+1 is like change-of-variables
3.997948202551132e-5
```
