### ISSUE TITLE
Make apply use a function call?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaApproximation/ContinuumArrays.jl#44]
Functions in this basis are represented by a lazy multiplication by a basis and a vector of coefficients:

```julia
julia> f = L*[1,2,3,4,5,6]
QuasiArrays.ApplyQuasiArray{Float64,1,typeof(*),Tuple{Spline{1,Float64},Array{Int64,1}}}(*, (Spline{1,Float64}([0.0, 0.2, 0.4, 0.6, 0.8, 1.0]), [1, 2, 3, 4, 5, 6]))

julia> axes(f)
(Inclusion(0.0..1.0),)

julia> f[0.1]
1.5
```

However, if it was `f(0.1)` at the end, not only would it look more like a function, but `f.([0.1,0.2])` would then work.

**Comment by dlfivefifty** [comment]
The idea is that ApproxFun will wrap this to make it act like a function. So functions-as-vectors and functions-as-functions will be two distinct concepts. 

If you want broadcast just use standard array indexing notation ` f[[0.1,0.2]] `

**Comment by ChrisRackauckas** [comment]
I see, makes sense.
