### ISSUE TITLE
Support Plotting

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ContinuumArrays.jl#89]
We should add support for plotting using grids/transforms. Anyone have an opinion on whether to support:

👍 Makie
🎉 Plots
🚀 Both

Please vote below. @jagot @TSGut 

Personally I think Makie will be really beneficial for complicated geometries like disks/triangles/etc. but perhaps Plots.jl can do this too...

**Comment by jagot** [comment]
I actually use neither, I use PyPlot.jl instead; as long as its not a required dependency, i.e. plotting is supported via [Requires.jl](https://github.com/JuliaPackaging/Requires.jl/), I'm fine with either. The other option is of course [RecipesBase.jl](https://github.com/JuliaPlots/RecipesBase.jl), for which there seems to be no Makie equivalent yet.

**Comment by dlfivefifty** [comment]
Actually meant:

👍 AbstractPlotting.jl (to support Makie.jl)
🎉 RecipesBase.jl (to support Plots.jl)
🚀 Both

Requires.jl might be a good solution.

**Comment by jagot** [comment]
RecipesBase.jl is lightweight, AbstractPlotting.jl not so much, so I would vote for Requires.jl 👀

**Comment by TSGut** [comment]
I feel like in most of the basic uses it's already fairly straightforward to make Plots.jl do the job. For higher dimensional more complicated domains where this would be a pain to manually set up, Makie is probably superior. So I somewhat hesitantly vote AbstractPlotting / Makie.

**Comment by dlfivefifty** [comment]
> RecipesBase.jl is lightweight, AbstractPlotting.jl not so much

Yes I agree... I find the existing of two different recipe formats pretty annoying...

Perhaps best to just make a new package ContinuumArraysAbstractPlotting.jl which is loaded manually for the time being... my understanding of Requires.jl is it is then easy to to have this loaded automatically.

**Comment by dlfivefifty** [comment]
Or... since the only packages that will use 3D are downstream (HarmonicOrthogonalPolynomials.jl and MultivariateOrthogonalPolynomials.jl) just put the dependency there

**Comment by dlfivefifty** [comment]
Annoyingly, Makie.jl (via WGLMakie.jl) doesn't seem to be very reliable in VSCode, and is very slow...

And regular Makie.jl + InfiniteArrays.jl triggers an obscure Julia type inference bug https://github.com/JuliaPlots/Makie.jl/issues/933

**Comment by TSGut** [comment]
Yeah WGLMakie even seems to state that it doesn't support VSCode yet on the documentation. Out of curiosity, is there a reason not to go for GLMakie?

**Comment by dlfivefifty** [comment]
OK we can use Plots.jl with the `plotly()` backend: the following gives a plot on a disk:
```julia
julia> plotly()
Plots.PlotlyBackend()

julia> r = range(0,1;length=100);

julia> x = r' .* cospi.(2r);

julia> y = r' .* sinpi.(2r);

julia> surface(x, y, exp.(x .+ cos.(y)))
```
Let's do this now.

(5 years ago I used to do live demos with Makie.jl of PDEs on a disk... annoying that the situation has seemed to have gone backwards...)

**Comment by dlfivefifty** [comment]
OK this now works:
```julia
using MultivariateOrthogonalPolynomials, Plots
plotly()
Z = Zernike()
xy = axes(Z,1)
x,y = first.(xy),last.(xy)
u = Z * (Z \ @.(cos(10x*y)))
surface(u)
```
